if(EXISTS "/mnt/c/Users/sehwanhong/CLionProjects/cs222-fall20-team-11/test/pfm/pfmtest_public[1]_tests.cmake")
  include("/mnt/c/Users/sehwanhong/CLionProjects/cs222-fall20-team-11/test/pfm/pfmtest_public[1]_tests.cmake")
else()
  add_test(pfmtest_public_NOT_BUILT pfmtest_public_NOT_BUILT)
endif()
