if(EXISTS "/mnt/c/Users/sehwanhong/CLionProjects/cs222-fall20-team-11/test/rbfm/rbfmtest_public[1]_tests.cmake")
  include("/mnt/c/Users/sehwanhong/CLionProjects/cs222-fall20-team-11/test/rbfm/rbfmtest_public[1]_tests.cmake")
else()
  add_test(rbfmtest_public_NOT_BUILT rbfmtest_public_NOT_BUILT)
endif()
