if(EXISTS "/mnt/c/Users/sehwanhong/CLionProjects/cs222-fall20-team-11/test/rbfm/rbfmtest_private[1]_tests.cmake")
  include("/mnt/c/Users/sehwanhong/CLionProjects/cs222-fall20-team-11/test/rbfm/rbfmtest_private[1]_tests.cmake")
else()
  add_test(rbfmtest_private_NOT_BUILT rbfmtest_private_NOT_BUILT)
endif()
