if(EXISTS "/mnt/c/Users/sehwanhong/CLionProjects/cs222-fall20-team-11/test/rm/rmtest_private[1]_tests.cmake")
  include("/mnt/c/Users/sehwanhong/CLionProjects/cs222-fall20-team-11/test/rm/rmtest_private[1]_tests.cmake")
else()
  add_test(rmtest_private_NOT_BUILT rmtest_private_NOT_BUILT)
endif()
