if(EXISTS "/mnt/c/Users/sehwanhong/CLionProjects/cs222-fall20-team-11/test/qe/qetest_public[1]_tests.cmake")
  include("/mnt/c/Users/sehwanhong/CLionProjects/cs222-fall20-team-11/test/qe/qetest_public[1]_tests.cmake")
else()
  add_test(qetest_public_NOT_BUILT qetest_public_NOT_BUILT)
endif()
